# Right one
# robot.turn(-21)
# robot.straight(-1340)
# robot.turn(-133)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()

# Left one
# robot.turn(17)
# robot.straight(-1360)
# robot.turn(100)
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()

# ----------------
# Middle one
# robot.turn(-2)
# robot.straight(-1270)
# robot.turn(-158)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# robot.straight(15)
# ev3.speaker.beep()
# ----------------
